### ISSUE TITLE
:granted pseudo-class is still active after taking back permission

### ISSUE THREAD

**Issue by arturgawlik** [WICG/PEPC#23]
First of all great job with new `<permission />` element - really like the concept behind. I've try to do little experiments with it and I think I found issue.
## Issue reproduction steps
I've created simple page that is using new `<permission />` HTML elements and I've done little styling for them - by default button's from `<permission />` elements has red backgroud color (indicating that permission is not granted). Then I'm clicking on one of the `<permission />` element and picking "Allow this time" button from permission browser dialog. In result appropriate "button" from `<permission />` element by gainng :granted pseudo class has green backgroud-color - so far so good. But problem occurs when I'm clicking on `<permission />` element second time and this time I'm picking "Stop allowing" button from permission browser dialog - in result of that `<permission />` element is still with green color - :granted pseudo class is still active and I'm thinking that this is wrong - after taking back permission :granted pseudo class should not match.

Screenshot from supplied reproduction repository:
<img width="490" alt="screenshot from application of supplied reproduction repository" src="https://github.com/WICG/PEPC/assets/26879804/9ff0e56a-84fa-4d64-bd82-e16f2455ce12">

## Repo with reproduction
https://github.com/arturgawlik/permission-html-element-experiments - repository contains index.html + style.css files. Please serve it with for example running vite local server `npx vite`

## Environment
Macbook Pro Apple M1
macOS Sonoma 
Chrome 126 (with "Experimental Web Platform features" enabled in chrome://flags)

**Comment by andypaicu** [comment]
Thank you for the report, I'll close this issue since it's more of a Chrome implementation bug, follow https://issuetracker.google.com/issues/347250842 for status updates on fixing the bug.
