### ISSUE TITLE
Confused about how to upgrade from "allow once" to "allow always"

### ISSUE THREAD

**Issue by tunetheweb** [WICG/PEPC#24]
I was testing this out on [the demo site](https://permission.site/pepc) and got really confused with how to upgrade from "allow once" to "allow all". For example, if I clicked "allow once" initially—either by accident, or on purpose until I'd decided this site was something I planned to use (and trust!) long term.

Consider the following flow:
- Visit page
- Click "Use camera"
- "Allow one time only"
- Oh that was an accident I meant to clock "allow all"
- Click button again to allow always. It seems I can't do it that way, I can only "continue allowing" or "stop allowing". Why would they not make it clear in this dialog it was "allow once" and also offer me an option to upgrade to "allow all"?
- Click "Stop allowing" to reset and start again.
- Click "Use camera" again to allow always this time.
- Hmmm... there's no Always option this time? I swear I saw that before!! Am I going mad? Why would they change the options?
- Uninstall Chrome and use another browser instead. It doesn't have this button, but at least permissions are in the one place rather than the confusing mess that is Chrome 😜 (jk, I work on Chrome!)

It seems the following ways do work to allow me to upgrade to allow all:
- Using the "Site permission" thingy (is there a name for this icon?!!?) in the omnibar to reset to allow always.
- Copying the URL, closing the tab, opening a new tab and clocking the button to "allow all" this time. Note just reloading in the current tab doesn't reset this (I can understand why, but less technical users may not).

I can understand there may be a desire to not over emphasise "allow all", and not sure if I have a real use case beyond this (somewhat contrived) example, but it threw me for a bit so thought I'd offer the feedback anyway.

**Comment by mharbach** [comment]
Thanks for sharing your experience. I agree that there are some modification paths that are not straightforward. This was a deliberate choice to make it less attractive for ill-meaning sites to keep pointing users at the button to try and extract a permanent grant from them in the same usage session. 

Additionally, we have heard early feedback that sites might be unlikely to keep a PEPC around after a grant was made (regardless of it being permanent or one-time), as they want to get on with their primary task (using the site for whatever purpose they came to visit). In that case, the grant would expire and the regular PEPC could be shown again on the next visit. 

A misclick on "allow this time" is admittedly a case that we are currently not handling well, but I'm not convinced that this is a common enough occurrence in real use cases (as you also mention) that would warrant us possibly increasing the abuse potential.

**Comment by tunetheweb** [comment]
Yup that's fair. As I said not entirely sure how valid this use case is. Happy to close, or leave open if you prefer.

**Comment by mharbach** [comment]
Thanks for bringing it up. I'll close it for now.
